[colors.primary]
background = '#463221'
foreground = '#f3e4d9'
 
[colors.cursor]
text = '#f3e4d9'
cursor = '#decbbd' 
 
[colors.vi_mode_cursor]
text = '#463221'
cursor = '#ffc080' 
 
[colors.search.matches]
foreground = '#6f5d51' 
background = '#ced69f' 
 
[colors.search.focused_match]
foreground = '#6f5d51' 
background = '#ffc080' 
 
[colors.footer_bar]
foreground = '#6f5d51' 
background = '#f3e4d9' 
 
[colors.hints.start]
foreground = '#6f5d51' 
background = '#ecc8ac' 
 
[colors.hints.end]
foreground = '#6f5d51' 
background = '#ecc8ac' 
 
[colors.selection]
text = '#463221'
background = '#ffc080'
 
 
[colors.normal]
black = '#181818' 
red = '#ffbab1' 
green = '#ffc080' 
yellow = '#b06924' 
blue = '#ffc080' 
magenta = '#ced69f' 
cyan = '#ecc8ac' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
