$image = /home/wesii/Pictures/wallpapers/Anime-Girl4.jpeg

$background = rgba(463221ff)

$error = rgba(ffbab1ff)

$error_container = rgba(e2000fff)

$inverse_on_surface = rgba(5a4b40ff)

$inverse_primary = rgba(b06924ff)

$inverse_surface = rgba(f3e4d9ff)

$on_background = rgba(f3e4d9ff)

$on_error = rgba(c00009ff)

$on_error_container = rgba(ffddd9ff)

$on_primary = rgba(884500ff)

$on_primary_container = rgba(ffe0c5ff)

$on_primary_fixed = rgba(713300ff)

$on_primary_fixed_variant = rgba(9f5707ff)

$on_secondary = rgba(6b4929ff)

$on_secondary_container = rgba(ffe0c5ff)

$on_secondary_fixed = rgba(623510ff)

$on_secondary_fixed_variant = rgba(7d5b3fff)

$on_surface = rgba(f3e4d9ff)

$on_surface_variant = rgba(decbbdff)

$on_tertiary = rgba(525d17ff)

$on_tertiary_container = rgba(e6edb6ff)

$on_tertiary_fixed = rgba(465400ff)

$on_tertiary_fixed_variant = rgba(626c32ff)

$outline = rgba(af9d90ff)

$outline_variant = rgba(6f5d51ff)

$primary = rgba(ffc080ff)

$primary_container = rgba(9f5707ff)

$primary_fixed = rgba(ffe0c5ff)

$primary_fixed_dim = rgba(ffc080ff)

$scrim = rgba(000000ff)

$secondary = rgba(ecc8acff)

$secondary_container = rgba(7d5b3fff)

$secondary_fixed = rgba(ffe0c5ff)

$secondary_fixed_dim = rgba(ecc8acff)

$shadow = rgba(000000ff)

$source_color = rgba(eb8f34ff)

$surface = rgba(463221ff)

$surface_bright = rgba(615249ff)

$surface_container = rgba(4c3c30ff)

$surface_container_high = rgba(54453aff)

$surface_container_highest = rgba(5d4f44ff)

$surface_container_low = rgba(4a392bff)

$surface_container_lowest = rgba(452d1bff)

$surface_dim = rgba(463221ff)

$surface_tint = rgba(ffc080ff)

$surface_variant = rgba(6f5d51ff)

$tertiary = rgba(ced69fff)

$tertiary_container = rgba(626c32ff)

$tertiary_fixed = rgba(e6edb6ff)

$tertiary_fixed_dim = rgba(ced69fff)

