# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f3e4d9"

# Title color for boxes
theme[title]="#ffc080"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ecc8ac"

# Background color of selected item in processes box
theme[selected_bg]="#ffc080"

# Foreground color of selected item in processes box
theme[selected_fg]="#884500"

# Color of inactive/disabled text
theme[inactive_fg]="#decbbd"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ced69f"

# Cpu box outline color
theme[cpu_box]="#af9d90"

# Memory/disks box outline color
theme[mem_box]="#af9d90"

# Net up/down box outline color
theme[net_box]="#af9d90"

# Processes box outline color
theme[proc_box]="#af9d90"

# Box divider line and small boxes line color
theme[div_line]="#6f5d51"

# Temperature graph colors
theme[temp_start]="#ecc8ac"
theme[temp_mid]="#ffc080"
theme[temp_end]="#ffbab1"

# CPU graph colors
theme[cpu_start]="#ecc8ac"
theme[cpu_mid]="#ffc080"
theme[cpu_end]="#ffbab1"

# Mem/Disk free meter
theme[free_start]="#ecc8ac"
theme[free_mid]=""
theme[free_end]="#7d5b3f"

# Mem/Disk cached meter
theme[cached_start]="#ced69f"
theme[cached_mid]=""
theme[cached_end]="#626c32"

# Mem/Disk available meter
theme[available_start]="#ffc080"
theme[available_mid]=""
theme[available_end]="#9f5707"

# Mem/Disk used meter
theme[used_start]="#ffbab1"
theme[used_mid]=""
theme[used_end]="#e2000f"

# Download graph colors
theme[download_start]="#ecc8ac"
theme[download_mid]="#ffc080"
theme[download_end]="#ced69f"

# Upload graph colors
theme[upload_start]="#ecc8ac"
theme[upload_mid]="#ffc080"
theme[upload_end]="#ced69f"