# SwayFX settings
blur enable
blur_xray disable
blur_passes 4
blur_radius 10

corner_radius 9

shadows enable
shadows_on_csd enable

default_dim_inactive 0.12

# Gaps and borders 
gaps inner 3
gaps outer 9
default_border pixel 3
default_floating_border pixel 3