# Focus follows mouse (equivalent to hyprland's follow_mouse = 1)
focus_follows_mouse yes

input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll no
    middle_emulation enabled
}

input type:mouse {
    scroll_factor 0.7
}