for_window [app_id="wallpaper-picker"] floating enable
for_window [app_id="wallpaper-picker"] border none
for_window [app_id="wallpaper-picker"] resize set width 1300 px height 400 px
for_window [app_id="wallpaper-picker"] move position center

for_window [app_id="sway_help"] floating enable
for_window [app_id="sway_help"] resize set width 900 px height 600 px
for_window [app_id="sway_help"] move position center

for_window [app_id="notifications"] floating enable
for_window [app_id="notifications"] resize set width 900 px height 600 px
for_window [app_id="notifications"] move position center

for_window [class="gsimplecal"] floating enable
for_window [class="gsimplecal"] move absolute position 8 34