# --- Main Colors ---
background            #463221
foreground            #f3e4d9
cursor                #f3e4d9
cursor_text_color     #463221

selection_background  #7d5b3f
selection_foreground  #ffe0c5

url_color             #ced69f

# --- ANSI Colors ---
color0                #463221
color1                #ffbab1
color2                #ced69f
color3                #ecc8ac
color4                #ffc080
color5                #ced69f
color6                #ecc8ac
color7                #f3e4d9

color8                #6f5d51
color9                #e2000f
color10               #626c32
color11               #7d5b3f
color12               #9f5707
color13               #7d5b3f
color14               #626c32
color15               #decbbd

# --- Starship Prompt Bubbles ---
color255              #9f5707
color254              #ffc080
color253              #7d5b3f
color252              #ecc8ac
color251              #626c32
color250              #ced69f
color249              #e2000f
color248              #ffbab1

color232              #ffe0c5
color233              #884500
color234              #ffe0c5
color235              #6b4929
color236              #e6edb6
color237              #525d17
color238              #ffddd9
color239              #c00009
color240              #ffe0c5

# Matched with unthemed light/dark
color243              #ffc080
color244              #ffbab1
color245              #6f5d51

# --- UI Elements ---
active_tab_foreground   #884500
active_tab_background   #ffc080
inactive_tab_foreground #ffe0c5
inactive_tab_background #9f5707

active_border_color     #ffc080
inactive_border_color   #af9d90

# --- Marks ---
mark1_foreground        #713300
mark1_background        #ffe0c5
mark2_foreground        #623510
mark2_background        #ffe0c5
mark3_foreground        #465400
mark3_background        #e6edb6
