" Matugen colorscheme — auto-generated by matugen, do not hand-edit
" Colors come from Material You palette derived from your wallpaper.
" Re-run matugen to update after changing wallpaper.

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

" ── Terminal ANSI palette (mirrors ghostty/kitty template) ──────────────────
" 0  surface_container_high  (black)
" 1  error                   (red)
" 2  primary                 (green)
" 3  tertiary                (yellow)
" 4  secondary               (blue)
" 5  primary_fixed           (magenta)
" 6  secondary_fixed         (cyan)
" 7  on_surface_variant      (white)
" 8  outline                 (bright black)
" 9  error_container         (bright red)
" 10 primary_container       (bright green)
" 11 tertiary_container      (bright yellow)
" 12 secondary_container     (bright blue)
" 13 inverse_primary         (bright magenta)
" 14 outline_variant         (bright cyan)
" 15 on_surface              (bright white)

let g:terminal_color_0  = "#3f494d"
let g:terminal_color_1  = "#ffbab1"
let g:terminal_color_2  = "#8cdaf3"
let g:terminal_color_3  = "#c6caf2"
let g:terminal_color_4  = "#b9d2db"
let g:terminal_color_5  = "#b4f0ff"
let g:terminal_color_6  = "#d1ebf3"
let g:terminal_color_7  = "#c6cfd4"
let g:terminal_color_8  = "#97a1a6"
let g:terminal_color_9  = "#e2000f"
let g:terminal_color_10 = "#00738b"
let g:terminal_color_11 = "#545a85"
let g:terminal_color_12 = "#47656f"
let g:terminal_color_13 = "#0089a5"
let g:terminal_color_14 = "#576266"
let g:terminal_color_15 = "#e1e7ea"

" ── Base UI ─────────────────────────────────────────────────────────────────
hi Normal        guibg=#29363c guifg=#e1e7ea
hi NormalNC      guibg=#29363c guifg=#c6cfd4
hi NormalFloat   guibg=#364044 guifg=#e1e7ea
hi FloatBorder   guibg=#364044 guifg=#97a1a6
hi FloatTitle    guibg=#364044 guifg=#8cdaf3 gui=bold
hi SignColumn    guibg=#29363c guifg=#97a1a6
hi EndOfBuffer   guibg=#29363c guifg=#576266
hi VertSplit     guibg=#29363c guifg=#576266
hi WinSeparator  guibg=#29363c guifg=#576266

" ── Status & Tab lines ──────────────────────────────────────────────────────
hi StatusLine    guibg=#8cdaf3 guifg=#005f72
hi StatusLineNC  guibg=#00738b guifg=#b4f0ff
hi TabLine       guibg=#364044 guifg=#c6cfd4
hi TabLineFill   guibg=#29363c guifg=#97a1a6
hi TabLineSel    guibg=#00738b guifg=#b4f0ff gui=bold

" ── Line numbers & cursor ────────────────────────────────────────────────────
hi LineNr        guibg=#29363c guifg=#97a1a6
hi CursorLineNr  guibg=#29363c guifg=#8cdaf3 gui=bold
hi CursorLine    guibg=#3f494d guifg=NONE
hi CursorColumn  guibg=#3f494d guifg=NONE
hi ColorColumn   guibg=#495356 guifg=NONE
hi Cursor        guibg=#8cdaf3 guifg=#005f72
hi lCursor       guibg=#b9d2db guifg=#2f545e

" ── Folds ───────────────────────────────────────────────────────────────────
hi FoldColumn    guibg=#29363c guifg=#97a1a6
hi Folded        guibg=#364044 guifg=#576266 gui=italic

" ── Search & Selection ──────────────────────────────────────────────────────
hi Search        guibg=#545a85 guifg=#e1e2ff
hi IncSearch     guibg=#c6caf2 guifg=#3f4574
hi CurSearch     guibg=#c6caf2 guifg=#3f4574
hi Visual        guibg=#47656f guifg=#d1ebf3
hi VisualNOS     guibg=#47656f guifg=#d1ebf3
hi Substitute    guibg=#e2000f guifg=#ffddd9

" ── Popup menu ──────────────────────────────────────────────────────────────
hi Pmenu         guibg=#364044 guifg=#e1e7ea
hi PmenuSel      guibg=#00738b guifg=#b4f0ff gui=bold
hi PmenuSbar     guibg=#3f494d guifg=NONE
hi PmenuThumb    guibg=#97a1a6 guifg=NONE
hi PmenuBorder   guibg=NONE guifg=#97a1a6
hi PmenuKind     guibg=#364044 guifg=#b9d2db
hi PmenuKindSel  guibg=#00738b guifg=#b9d2db
hi PmenuExtra    guibg=#364044 guifg=#c6cfd4
hi PmenuExtraSel guibg=#00738b guifg=#c6cfd4

" ── Messages & errors ────────────────────────────────────────────────────────
hi Error         guibg=#e2000f guifg=#ffddd9
hi ErrorMsg      guibg=#e2000f guifg=#ffddd9
hi WarningMsg    guibg=NONE guifg=#c6caf2
hi InfoMsg       guibg=NONE guifg=#b9d2db
hi ModeMsg       guibg=NONE guifg=#8cdaf3 gui=bold
hi MoreMsg       guibg=NONE guifg=#8cdaf3
hi Question      guibg=NONE guifg=#8cdaf3

" ── Misc UI ─────────────────────────────────────────────────────────────────
hi NonText       guibg=NONE guifg=#576266
hi SpecialKey    guibg=NONE guifg=#97a1a6
hi Conceal       guibg=NONE guifg=#97a1a6
hi Directory     guibg=NONE guifg=#b9d2db
hi Title         guibg=NONE guifg=#8cdaf3 gui=bold
hi WildMenu      guibg=#00738b guifg=#b4f0ff
hi MatchParen    guibg=#545a85 guifg=#e1e2ff gui=bold
hi QuickFixLine  guibg=#00738b guifg=#b4f0ff
hi debugPC       guibg=#47656f guifg=#d1ebf3
hi debugBreakpoint guibg=#e2000f guifg=#ffddd9

" ── Diffs ───────────────────────────────────────────────────────────────────
hi DiffAdd       guibg=#545a85 guifg=NONE
hi DiffChange    guibg=#47656f guifg=NONE
hi DiffDelete    guibg=#e2000f guifg=#ffddd9
hi DiffText      guibg=#c6caf2 guifg=#3f4574

" ── Spelling ────────────────────────────────────────────────────────────────
hi SpellBad      guibg=NONE guifg=#ffbab1 gui=undercurl guisp=#ffbab1
hi SpellCap      guibg=NONE guifg=#c6caf2 gui=undercurl guisp=#c6caf2
hi SpellRare     guibg=NONE guifg=#b9d2db gui=undercurl guisp=#b9d2db
hi SpellLocal    guibg=NONE guifg=#8cdaf3 gui=undercurl guisp=#8cdaf3

" ── Syntax ──────────────────────────────────────────────────────────────────
hi Comment       guibg=NONE guifg=#3c4447 gui=italic
hi Constant      guibg=NONE guifg=#4c585e
hi String        guibg=NONE guifg=#4d585e
hi Character     guibg=NONE guifg=#4d585e
hi Number        guibg=NONE guifg=#4c585e
hi Boolean       guibg=NONE guifg=#4c585e
hi Float         guibg=NONE guifg=#4c585e
hi Identifier    guibg=NONE guifg=#4d585f
hi Function      guibg=NONE guifg=#4d585e
hi Statement     guibg=NONE guifg=#4d585e
hi Conditional   guibg=NONE guifg=#4d585e
hi Repeat        guibg=NONE guifg=#4d585e
hi Label         guibg=NONE guifg=#4c575d
hi Operator      guibg=NONE guifg=#535c60
hi Keyword       guibg=NONE guifg=#4d585e gui=bold
hi Exception     guibg=NONE guifg=#ffbab1
hi PreProc       guibg=NONE guifg=#4d585e
hi Include       guibg=NONE guifg=#4d585e
hi Define        guibg=NONE guifg=#4d585e
hi Macro         guibg=NONE guifg=#4d585e
hi PreCondit     guibg=NONE guifg=#4d585e
hi Type          guibg=NONE guifg=#4c575d
hi StorageClass  guibg=NONE guifg=#4c575d
hi Structure     guibg=NONE guifg=#4c575d
hi Typedef       guibg=NONE guifg=#4c575d
hi Special       guibg=NONE guifg=#4d585e
hi SpecialChar   guibg=NONE guifg=#4d585e
hi Tag           guibg=NONE guifg=#4d585e
hi Delimiter     guibg=NONE guifg=#535c60
hi SpecialComment guibg=NONE guifg=#3c4447 gui=bold
hi Debug         guibg=NONE guifg=#ffbab1
hi Underlined    guibg=NONE guifg=#b9d2db gui=underline
hi Ignore        guibg=NONE guifg=#576266
hi Todo          guibg=#545a85 guifg=#e1e2ff gui=bold

" ── Treesitter (semantic token) overrides ───────────────────────────────────
hi! link @variable              Identifier
hi! link @variable.builtin      Special
hi! link @variable.parameter    Identifier
hi! link @variable.member       Identifier
hi! link @constant              Constant
hi! link @constant.builtin      Special
hi! link @constant.macro        Define
hi! link @module                Structure
hi! link @module.builtin        Special
hi! link @label                 Label
hi! link @string                String
hi! link @string.documentation  SpecialComment
hi! link @string.regexp         SpecialChar
hi! link @string.escape         SpecialChar
hi! link @string.special        SpecialChar
hi! link @character             Character
hi! link @character.special     SpecialChar
hi! link @boolean               Boolean
hi! link @number                Number
hi! link @number.float          Float
hi! link @type                  Type
hi! link @type.builtin          Special
hi! link @type.definition       Typedef
hi! link @attribute             PreProc
hi! link @property              Identifier
hi! link @function              Function
hi! link @function.builtin      Special
hi! link @function.call         Function
hi! link @function.macro        Macro
hi! link @function.method       Function
hi! link @function.method.call  Function
hi! link @constructor           Function
hi! link @operator              Operator
hi! link @keyword               Keyword
hi! link @keyword.coroutine     Special
hi! link @keyword.function      Keyword
hi! link @keyword.operator      Operator
hi! link @keyword.import        Include
hi! link @keyword.type          Keyword
hi! link @keyword.modifier      Keyword
hi! link @keyword.repeat        Repeat
hi! link @keyword.return        Keyword
hi! link @keyword.debug         Debug
hi! link @keyword.exception     Exception
hi! link @keyword.conditional   Conditional
hi! link @keyword.directive     Define
hi! link @keyword.directive.define Define
hi! link @punctuation.delimiter Delimiter
hi! link @punctuation.bracket   Delimiter
hi! link @punctuation.special   SpecialChar
hi! link @comment               Comment
hi! link @comment.documentation SpecialComment
hi! link @comment.error         Error
hi! link @comment.warning       WarningMsg
hi! link @comment.todo          Todo
hi! link @comment.note          SpecialComment
hi! link @markup.strong         Title
hi! link @markup.italic         Comment
hi! link @markup.strikethrough  Comment
hi! link @markup.underline      Underlined
hi! link @markup.heading        Title
hi! link @markup.quote          Comment
hi! link @markup.math           Special
hi! link @markup.link           Underlined
hi! link @markup.link.label     Title
hi! link @markup.raw            String
hi! link @markup.list           Statement
hi! link @diff.plus             DiffAdd
hi! link @diff.minus            DiffDelete
hi! link @diff.delta            DiffChange
hi! link @tag                   Tag
hi! link @tag.builtin           Special
hi! link @tag.attribute         Identifier
hi! link @tag.delimiter         Delimiter

" ── LSP semantic tokens ──────────────────────────────────────────────────────
hi! link @lsp.type.class         Type
hi! link @lsp.type.comment       Comment
hi! link @lsp.type.decorator     Function
hi! link @lsp.type.enum          Type
hi! link @lsp.type.enumMember   Constant
hi! link @lsp.type.function      Function
hi! link @lsp.type.interface     Type
hi! link @lsp.type.keyword       Keyword
hi! link @lsp.type.macro         Macro
hi! link @lsp.type.method        Function
hi! link @lsp.type.modifier      Keyword
hi! link @lsp.type.namespace     Structure
hi! link @lsp.type.number        Number
hi! link @lsp.type.operator      Operator
hi! link @lsp.type.parameter     Identifier
hi! link @lsp.type.property      Identifier
hi! link @lsp.type.regexp        SpecialChar
hi! link @lsp.type.string        String
hi! link @lsp.type.struct        Structure
hi! link @lsp.type.type          Type
hi! link @lsp.type.typeParameter Typedef
hi! link @lsp.type.variable      Identifier

" ── LSP Diagnostics ─────────────────────────────────────────────────────────
hi DiagnosticError            guibg=NONE guifg=#ffbab1
hi DiagnosticWarn             guibg=NONE guifg=#c6caf2
hi DiagnosticInfo             guibg=NONE guifg=#b9d2db
hi DiagnosticHint             guibg=NONE guifg=#8cdaf3
hi DiagnosticOk               guibg=NONE guifg=#545a85

hi DiagnosticUnderlineError   guibg=NONE gui=undercurl guisp=#ffbab1
hi DiagnosticUnderlineWarn    guibg=NONE gui=undercurl guisp=#c6caf2
hi DiagnosticUnderlineInfo    guibg=NONE gui=undercurl guisp=#b9d2db
hi DiagnosticUnderlineHint    guibg=NONE gui=undercurl guisp=#8cdaf3
hi DiagnosticUnderlineOk      guibg=NONE gui=undercurl guisp=#545a85

hi DiagnosticVirtualTextError guibg=#e2000f guifg=#ffddd9
hi DiagnosticVirtualTextWarn  guibg=#545a85 guifg=#e1e2ff
hi DiagnosticVirtualTextInfo  guibg=#47656f guifg=#d1ebf3
hi DiagnosticVirtualTextHint  guibg=#00738b guifg=#b4f0ff
hi DiagnosticVirtualTextOk    guibg=#545a85 guifg=#e1e2ff

hi DiagnosticSignError        guibg=NONE guifg=#ffbab1
hi DiagnosticSignWarn         guibg=NONE guifg=#c6caf2
hi DiagnosticSignInfo         guibg=NONE guifg=#b9d2db
hi DiagnosticSignHint         guibg=NONE guifg=#8cdaf3
hi DiagnosticSignOk           guibg=NONE guifg=#545a85

hi DiagnosticFloatingError    guibg=NONE guifg=#ffbab1
hi DiagnosticFloatingWarn     guibg=NONE guifg=#c6caf2
hi DiagnosticFloatingInfo     guibg=NONE guifg=#b9d2db
hi DiagnosticFloatingHint     guibg=NONE guifg=#8cdaf3
