# hide_window_decorations yes

cursor_trail 1

background_opacity 0.73
window_padding_width 4

font_family Jetbrains Mono NerdFont
font_family JetBrainsMono Nerd Font Mono
font_size 16.0


include themes/Matugen.conf



