[config]
prefer = "value"

[config.wallpaper]
command = "awww img --transition-type grow {{ image }}  --transition-duration 4"
set = true

# ----------------------------------------------------
#  WINDOW MANAGER & COMPOSITORS
# ----------------------------------------------------
[templates.sway]
input_path = '~/.config/matugen/templates/sway-colors.conf'
output_path = '~/.config/sway/colors.conf'
post_hook = 'swaymsg reload'

[templates.sway-palette]
input_path = '~/.config/matugen/templates/sway-palette.conf'
output_path = '~/.config/sway/palette.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar || true'

[templates.wofi]
input_path = '~/.config/matugen/templates/wofi.css'
output_path = '~/.config/wofi/colors.css'

# ----------------------------------------------------
#  THEME ENGINES & GRAPHICS (GTK / QT )
# ----------------------------------------------------
[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.themes/adw-gtk3-dark/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.themes/adw-gtk3-dark/gtk-4.0/colors.css"
post_hook = 'bash ~/.config/matugen/gtk-reload.sh'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'


# ----------------------------------------------------
#  TERMINALS & SHELLS
# ----------------------------------------------------
[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty || true'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = 'pkill -SIGUSR1 kitty || true'
# ----------------------------------------------------
#  EDITORS & UTILITIES
# ----------------------------------------------------
[templates.nvim]
input_path = '~/.config/matugen/templates/nvim.vim'
output_path = '~/.config/nvim/colors/matugen.vim'
post_hook = 'pkill -SIGUSR1 nvim || true'

[templates.vscodium]
input_path = '~/.config/matugen/templates/vscodium.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload || true'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/colors.css'

# ----------------------------------------------------
#  MEDIA & SYSTEM MONITORING
# ----------------------------------------------------
[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava || true'

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.opencode]
input_path = '~/.config/matugen/templates/opencode.json'
output_path = '~/.config/opencode/themes/matugen.json'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.config/quickshell/generated/colors.json'
post_hook = 'quickshell kill >/dev/null 2>&1 || true; qs -d >/dev/null 2>&1'


[templates.gtklock]
input_path = '~/.config/matugen/templates/gtklock.css'
output_path = '~/.config/gtklock/colors.css'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Documents/notes/.obsidian/snippets/matugen.css'
